/**
 * Builder classes for referral_http test data.
 *
 * This file contains two types of builders (following Python agent pattern):
 * 1. Entity Builders - For constructing domain objects/entities
 * 2. Parameter Builders - For constructing test input data (configs, maps)
 *
 * The builder pattern makes test input-output relationships crystal clear:
 * - Input: Built with fluent API showing exactly what's being tested
 * - Output: Assertions verify expected behavior based on input
 *
 * Example:
 *   // Clear input construction
 *   final config = BonusConfigBuilder()
 *       .withCriticalDates(['2025-12-25'])
 *       .build();
 *
 *   // Clear expected output
 *   expect(getDayCategory(date, config), DayCategory.critical);
 *
 * Benefits:
 * - Maintainable: Change structure? Update builder once
 * - Readable: Fluent API makes test intent clear
 * - Reusable: Share builders across test files
 *
 * Generated by Flutter Unit Test Agent
 */

import 'package:snabbit_runner/referrals/services/referral_http.dart';

class ReferralHttpBuilder {
  // TODO: Add fields matching ReferralHttp constructor

  ReferralHttpBuilder();

  ReferralHttp build() {
    // TODO: Construct ReferralHttp instance with test data
    return ReferralHttp(
      // TODO: Add constructor parameters
    );
  }

  // Fluent builder methods
  // TODO: Add with* methods for each field
  // Example:
  // ReferralHttpBuilder withFieldName(Type value) {
  //   _fieldName = value;
  //   return this;
  // }

  // Scenario methods (following Python agent pattern)
  ReferralHttpBuilder asHighValue() {
    // TODO: Set up high-value scenario
    return this;
  }

  ReferralHttpBuilder asLowValue() {
    // TODO: Set up low-value scenario
    return this;
  }

  ReferralHttpBuilder asEdgeCase() {
    // TODO: Set up edge case scenario (nulls, empty collections, etc.)
    return this;
  }
}
