// Mocks generated by Mockito 5.4.6 from annotations
// in snabbit_runner/test/unit/services/iot/flush/flush_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:snabbit_runner/services/iot/cleanup/cleanup_job.dart' as _i4;
import 'package:snabbit_runner/services/iot/sender/sender.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Sender].
///
/// See the documentation for Mockito's code generation for more information.
class MockSender extends _i1.Mock implements _i2.Sender {
  MockSender() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> sendAllData(
    String? userId,
    String? endpoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAllData,
          [
            userId,
            endpoint,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [CleanupJob].
///
/// See the documentation for Mockito's code generation for more information.
class MockCleanupJob extends _i1.Mock implements _i4.CleanupJob {
  MockCleanupJob() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> cleanupSentBatteryData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupSentBatteryData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupSentLocationData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupSentLocationData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupSentDeviceStateData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupSentDeviceStateData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupSentData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupSentData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupBatteryData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupBatteryData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupLocationData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupLocationData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupDeviceStateData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupDeviceStateData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupAllData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupAllData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteAllUserData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllUserData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
