/**
 * Builder classes for info_banner test data.
 *
 * This file contains two types of builders (following Python agent pattern):
 * 1. Entity Builders - For constructing domain objects/entities
 * 2. Parameter Builders - For constructing test input data (configs, maps)
 *
 * The builder pattern makes test input-output relationships crystal clear:
 * - Input: Built with fluent API showing exactly what's being tested
 * - Output: Assertions verify expected behavior based on input
 *
 * Example:
 *   // Clear input construction
 *   final config = BonusConfigBuilder()
 *       .withCriticalDates(['2025-12-25'])
 *       .build();
 *
 *   // Clear expected output
 *   expect(getDayCategory(date, config), DayCategory.critical);
 *
 * Benefits:
 * - Maintainable: Change structure? Update builder once
 * - Readable: Fluent API makes test intent clear
 * - Reusable: Share builders across test files
 *
 * Generated by Flutter Unit Test Agent
 */

import 'package:snabbit_runner/home/models/info_banner.dart';

class InfoBannerModelBuilder {
  String? _title;
  String? _subtitle;
  Map<String, dynamic>? _bgImage;
  Map<String, dynamic>? _icon;

  InfoBannerModelBuilder();

  /// Creates a default valid JSON for InfoBannerModel.fromJson
  static Map<String, dynamic> defaultJson() {
    return {
      'title': 'Test Banner Title',
      'subtitle': 'Test Banner Subtitle',
      'bg': {'url': 'https://example.com/bg.png'},
      'icon': {'url': 'https://example.com/icon.png'},
    };
  }

  /// Creates JSON with specified null fields for testing null handling
  static Map<String, dynamic> jsonWith({
    bool nullTitle = false,
    bool nullSubtitle = false,
    bool nullBg = false,
    bool nullIcon = false,
  }) {
    return {
      'title': nullTitle ? null : 'Test Title',
      'subtitle': nullSubtitle ? null : 'Test Subtitle',
      'bg': nullBg ? null : {'url': 'https://example.com/bg.png'},
      'icon': nullIcon ? null : {'url': 'https://example.com/icon.png'},
    };
  }

  /// Creates invalid/edge case JSON for testing error handling
  static Map<String, dynamic> invalidJson() {
    return <String, dynamic>{};  // Empty map - all fields will be null
  }

  InfoBannerModel build() {
    return InfoBannerModel(
      title: _title,
      subtitle: _subtitle,
    );
  }

  // Fluent builder methods
  InfoBannerModelBuilder withTitle(String? value) {
    _title = value;
    return this;
  }

  InfoBannerModelBuilder withSubtitle(String? value) {
    _subtitle = value;
    return this;
  }

  // Scenario methods (following Python agent pattern)
  InfoBannerModelBuilder asHighValue() {
    _title = 'Important Banner';
    _subtitle = 'High priority message';
    return this;
  }

  InfoBannerModelBuilder asLowValue() {
    _title = 'Info';
    _subtitle = null;
    return this;
  }

  InfoBannerModelBuilder asEdgeCase() {
    _title = null;
    _subtitle = null;
    return this;
  }
}
