// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.snabbit.runner.remoteconfig.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object RemoteConfigApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class RemoteConfigApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * Dart → KMP (method channel). Flutter pushes the Remote Config bool flags the
 * native module needs (e.g. `expert_show_earnings`) so KMP screens can gate on
 * them without their own Firebase dependency.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface RemoteConfigHostApi {
  /**
   * Replace the native-side snapshot of RC bool flags. Called after each
   * fetch-and-activate and on real-time config updates, so KMP always reads
   * the latest values. A key absent from [flags] falls back to the KMP-side
   * caller default (safe when RC is unavailable).
   */
  fun setBoolFlags(flags: Map<String, Boolean>)
  /**
   * Replace the native-side snapshot of RC **string** flags (e.g. JSON config
   * like `expert_vishwaas_banner`). Same semantics as [setBoolFlags]: a key
   * absent from [flags] falls back to the KMP-side caller default.
   */
  fun setStringFlags(flags: Map<String, String>)

  companion object {
    /** The codec used by RemoteConfigHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      RemoteConfigApiPigeonCodec()
    }
    /** Sets up an instance of `RemoteConfigHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RemoteConfigHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.RemoteConfigHostApi.setBoolFlags$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val flagsArg = args[0] as Map<String, Boolean>
            val wrapped: List<Any?> = try {
              api.setBoolFlags(flagsArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteConfigApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.RemoteConfigHostApi.setStringFlags$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val flagsArg = args[0] as Map<String, String>
            val wrapped: List<Any?> = try {
              api.setStringFlags(flagsArg)
              listOf(null)
            } catch (exception: Throwable) {
              RemoteConfigApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
