// Mocks generated by Mockito 5.4.6 from annotations
// in snabbit_runner/test/unit/services/iot/sender/sender_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:snabbit_runner/models/battery_data.dart' as _i5;
import 'package:snabbit_runner/models/device_state_data.dart' as _i9;
import 'package:snabbit_runner/models/location_data.dart' as _i7;
import 'package:snabbit_runner/services/database/database_interface.dart'
    as _i2;
import 'package:snabbit_runner/services/iot/collectors/battery_collector.dart'
    as _i4;
import 'package:snabbit_runner/services/iot/collectors/device_state_collector.dart'
    as _i8;
import 'package:snabbit_runner/services/iot/collectors/location_collector.dart'
    as _i6;
import 'package:snabbit_runner/services/iot/http/iot_http.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IDatabaseInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabaseInterface extends _i1.Mock
    implements _i2.IDatabaseInterface {
  MockIDatabaseInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            data,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> query(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
    String? orderBy,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
            #orderBy: orderBy,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> count(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> execute(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [BatteryCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatteryCollector extends _i1.Mock implements _i4.BatteryCollector {
  MockBatteryCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> collect(
    String? userId, {
    required int? collectionCycleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collect,
          [userId],
          {#collectionCycleId: collectionCycleId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getUnsentCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUnsentCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.BatteryData>> getUnsent(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsent,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i3.Future<List<_i5.BatteryData>>.value(<_i5.BatteryData>[]),
      ) as _i3.Future<List<_i5.BatteryData>>);
}

/// A class which mocks [LocationCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationCollector extends _i1.Mock implements _i6.LocationCollector {
  MockLocationCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> collect(
    String? userId, {
    required int? collectionCycleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collect,
          [userId],
          {#collectionCycleId: collectionCycleId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getUnsentCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUnsentCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i7.LocationData>> getUnsent(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsent,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i3.Future<List<_i7.LocationData>>.value(<_i7.LocationData>[]),
      ) as _i3.Future<List<_i7.LocationData>>);

  @override
  _i3.Future<_i7.LocationData?> getLastCollected(
    String? userId, {
    int? maxAgeSeconds = 60,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastCollected,
          [userId],
          {#maxAgeSeconds: maxAgeSeconds},
        ),
        returnValue: _i3.Future<_i7.LocationData?>.value(),
      ) as _i3.Future<_i7.LocationData?>);
}

/// A class which mocks [DeviceStateCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceStateCollector extends _i1.Mock
    implements _i8.DeviceStateCollector {
  MockDeviceStateCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> collect(
    String? userId, {
    required int? collectionCycleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collect,
          [userId],
          {#collectionCycleId: collectionCycleId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getUnsentCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUnsentCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i9.DeviceStateData>> getUnsent(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsent,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i9.DeviceStateData>>.value(
            <_i9.DeviceStateData>[]),
      ) as _i3.Future<List<_i9.DeviceStateData>>);
}

/// A class which mocks [IotHttp].
///
/// See the documentation for Mockito's code generation for more information.
class MockIotHttp extends _i1.Mock implements _i10.IotHttp {
  MockIotHttp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> sendIotData({
    required String? endpoint,
    required String? userId,
    required List<Map<String, dynamic>>? batteries,
    required List<Map<String, dynamic>>? locations,
    List<Map<String, dynamic>>? deviceStates = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendIotData,
          [],
          {
            #endpoint: endpoint,
            #userId: userId,
            #batteries: batteries,
            #locations: locations,
            #deviceStates: deviceStates,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
