// Mocks generated by Mockito 5.4.6 from annotations
// in snabbit_runner/test/unit/services/iot/foreground_fallback/iot_foreground_fallback_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:snabbit_runner/services/database/database_interface.dart'
    as _i2;
import 'package:snabbit_runner/services/iot/config/config_service.dart' as _i6;
import 'package:snabbit_runner/services/iot/diagnostics/iot_diagnostics_collector.dart'
    as _i5;
import 'package:snabbit_runner/services/iot/sender/sender.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IDatabaseInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabaseInterface extends _i1.Mock
    implements _i2.IDatabaseInterface {
  MockIDatabaseInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> insert(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            data,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<Map<String, dynamic>>> query(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
    String? orderBy,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
            #orderBy: orderBy,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<int> update(
    String? table,
    Map<String, dynamic>? values, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            values,
          ],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> delete(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> count(
    String? table, {
    String? where,
    List<dynamic>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> execute(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Sender].
///
/// See the documentation for Mockito's code generation for more information.
class MockSender extends _i1.Mock implements _i4.Sender {
  MockSender() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> sendAllData(
    String? userId,
    String? endpoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAllData,
          [
            userId,
            endpoint,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [IotDiagnosticsCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockIotDiagnosticsCollector extends _i1.Mock
    implements _i5.IotDiagnosticsCollector {
  MockIotDiagnosticsCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logDiagnostic(
    String? eventName,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDiagnostic,
          [
            eventName,
            data,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i6.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get apiEnabled => (super.noSuchMethod(
        Invocation.getter(#apiEnabled),
        returnValue: false,
      ) as bool);

  @override
  int get batteryCollectionInterval => (super.noSuchMethod(
        Invocation.getter(#batteryCollectionInterval),
        returnValue: 0,
      ) as int);

  @override
  int get sendInterval => (super.noSuchMethod(
        Invocation.getter(#sendInterval),
        returnValue: 0,
      ) as int);

  @override
  int get maxBatteryRecords => (super.noSuchMethod(
        Invocation.getter(#maxBatteryRecords),
        returnValue: 0,
      ) as int);

  @override
  int get maxLocationRecords => (super.noSuchMethod(
        Invocation.getter(#maxLocationRecords),
        returnValue: 0,
      ) as int);

  @override
  int get deviceStateCollectionInterval => (super.noSuchMethod(
        Invocation.getter(#deviceStateCollectionInterval),
        returnValue: 0,
      ) as int);

  @override
  int get maxDeviceStateRecords => (super.noSuchMethod(
        Invocation.getter(#maxDeviceStateRecords),
        returnValue: 0,
      ) as int);

  @override
  int get apiTimeout => (super.noSuchMethod(
        Invocation.getter(#apiTimeout),
        returnValue: 0,
      ) as int);

  @override
  int get cleanupInterval => (super.noSuchMethod(
        Invocation.getter(#cleanupInterval),
        returnValue: 0,
      ) as int);

  @override
  int get killSwitchMaxWait => (super.noSuchMethod(
        Invocation.getter(#killSwitchMaxWait),
        returnValue: 0,
      ) as int);

  @override
  bool get fgFallbackEnabled => (super.noSuchMethod(
        Invocation.getter(#fgFallbackEnabled),
        returnValue: false,
      ) as bool);

  @override
  int get fgFallbackStalenessThresholdSeconds => (super.noSuchMethod(
        Invocation.getter(#fgFallbackStalenessThresholdSeconds),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int getLocationInterval(String? status) => (super.noSuchMethod(
        Invocation.method(
          #getLocationInterval,
          [status],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool hasIntervalsChanged(Map<String, int>? oldIntervals) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasIntervalsChanged,
          [oldIntervals],
        ),
        returnValue: false,
      ) as bool);
}
