// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.snabbit.runner.navigation.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NavigationApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class NavCommandType(val raw: Int) {
  /**
   * Navigate to a Flutter-owned route ([NavCommand.route] + [NavCommand.args]) —
   * a terminal handoff (the native host finishes).
   */
  OPEN_FLUTTER_ROUTE(0),
  /**
   * Push a Flutter route while KEEPING the native host alive behind it (the
   * reordering round trip). Dismissing it calls [NavigationHostApi.returnToNativeHost].
   */
  PUSH_HOST_BACKED_ROUTE(1),
  /**
   * The native root-shell host just became the resumed foreground surface —
   * Dart should drain any deeplink held for the cohort ([NavCommand.route] is
   * unused/empty). This makes a held deeplink open ON TOP of the now-foreground
   * shell, so a shell that launches/re-launches never covers it.
   */
  DRAIN_DEEPLINKS(2);

  companion object {
    fun ofRaw(raw: Int): NavCommandType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A command the native navigation host asks Flutter to execute (KMP → Dart,
 * event channel). Currently the single cross-world action is opening a
 * Flutter-owned route during a native → Flutter handoff.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NavCommand (
  val type: NavCommandType,
  /** Flutter route name. Always set — every command type carries a route. */
  val route: String,
  /** Optional string arguments for the route. */
  val args: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NavCommand {
      val type = pigeonVar_list[0] as NavCommandType
      val route = pigeonVar_list[1] as String
      val args = pigeonVar_list[2] as Map<String?, String?>?
      return NavCommand(type, route, args)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      route,
      args,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NavCommand
    return NavigationApiPigeonUtils.deepEquals(this.type, other.type) && NavigationApiPigeonUtils.deepEquals(this.route, other.route) && NavigationApiPigeonUtils.deepEquals(this.args, other.args)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NavigationApiPigeonUtils.deepHash(this.type)
    result = 31 * result + NavigationApiPigeonUtils.deepHash(this.route)
    result = 31 * result + NavigationApiPigeonUtils.deepHash(this.args)
    return result
  }
  override fun toString(): String {
    return "NavCommand(type=$type, route=$route, args=$args)"
  }
}
private open class NavigationApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NavCommandType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NavCommand.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NavCommandType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NavCommand -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val NavigationApiPigeonMethodCodec = StandardMethodCodec(NavigationApiPigeonCodec())


/**
 * Dart → KMP (method channel). Drives the native (Compose) navigation host.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NavigationHostApi {
  /**
   * Open a registered native destination (launches the native host). Returns
   * `true` if a native screen owns the key (and was opened), `false` otherwise —
   * the caller decides how to handle a `false` (the module renders no error UI).
   */
  fun openNativeDestination(key: String, args: Map<String?, String?>): Boolean
  /**
   * Open a native destination and await its result (the
   * `startActivityForResult` equivalent). Completes with the result map the
   * native screen returned, or `null` if the screen was dismissed without one.
   */
  fun openNativeDestinationForResult(key: String, args: Map<String?, String?>, callback: (Result<Map<String?, String?>?>) -> Unit)
  /**
   * Route an already-resolved deep-link value to a native destination.
   * Returns true if a native screen owns it (and the host was opened); false
   * lets the Dart DeepLinkRouter keep handling the value as a Flutter route.
   */
  fun handleResolvedDeeplink(value: String, params: Map<String?, String?>): Boolean
  /**
   * Deep-link keep-host handoff for a Flutter-owned destination. When a native
   * root-shell host is currently live (the MQTT-cohort shell is foreground), it
   * brings Flutter to front (keeping the host alive behind it) and opens [route]
   * (+ [args]) as a host-backed route so back returns to the shell; returns `true`.
   * Returns `false` when no root-shell host is live — the caller then navigates
   * on Flutter itself (unchanged behaviour for non-cohort runners).
   */
  fun openDeeplinkViaHost(route: String, args: Map<String?, String?>): Boolean
  /**
   * True when the native root-shell host (the MQTT-cohort bottom-nav shell) is
   * currently the RESUMED foreground surface. The deeplink router uses this to
   * HOLD a cohort deeplink until the shell is actually up — so the linked screen
   * opens ON TOP of the shell (drained on the shell's onResume) instead of being
   * covered by a shell that launches/re-launches afterward.
   */
  fun isRootShellForeground(): Boolean
  /**
   * Loan deep-link, native path: ask the RUNNING root-shell (the MQTT-cohort
   * bottom-nav shell) to switch to the Profile tab and open the native loan sheet.
   * Loan is migrated — it lives inside the Profile tab, not as a standalone screen,
   * so this stays on the shell (no keep-host handoff) and signals it in-place.
   * Returns `true` when the shell took it; `false` when no root-shell host is the
   * foreground surface — the caller then shows the Flutter loan sheet (unchanged
   * behaviour for non-cohort runners).
   */
  fun showLoanInShell(): Boolean
  /**
   * Pop the native back stack (the host finishes when it empties, returning to
   * Flutter — single-active-surface).
   */
  fun back()
  /**
   * Return to a host-backed native screen the user handed off from (the reordering
   * round trip). Reorders the live native host to front, or recreates it from its
   * stashed key+args if the OS reclaimed it while backgrounded.
   */
  fun returnToNativeHost(callback: (Result<Unit>) -> Unit)
  /**
   * Forced-logout teardown: finish the native shell (NavigationHostActivity) so the
   * Flutter login screen — already pushed by handle403() on the Flutter navigator
   * underneath — becomes the foreground surface. No-op when no native host is alive
   * (non-cohort runners, or the runner is already on Flutter).
   */
  fun exitNativeShell()

  companion object {
    /** The codec used by NavigationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NavigationApiPigeonCodec()
    }
    /** Sets up an instance of `NavigationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NavigationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.openNativeDestination$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val argsArg = args[1] as Map<String?, String?>
            val wrapped: List<Any?> = try {
              listOf(api.openNativeDestination(keyArg, argsArg))
            } catch (exception: Throwable) {
              NavigationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.openNativeDestinationForResult$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val argsArg = args[1] as Map<String?, String?>
            api.openNativeDestinationForResult(keyArg, argsArg) { result: Result<Map<String?, String?>?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NavigationApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.handleResolvedDeeplink$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val valueArg = args[0] as String
            val paramsArg = args[1] as Map<String?, String?>
            val wrapped: List<Any?> = try {
              listOf(api.handleResolvedDeeplink(valueArg, paramsArg))
            } catch (exception: Throwable) {
              NavigationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.openDeeplinkViaHost$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routeArg = args[0] as String
            val argsArg = args[1] as Map<String?, String?>
            val wrapped: List<Any?> = try {
              listOf(api.openDeeplinkViaHost(routeArg, argsArg))
            } catch (exception: Throwable) {
              NavigationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.isRootShellForeground$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isRootShellForeground())
            } catch (exception: Throwable) {
              NavigationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.showLoanInShell$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.showLoanInShell())
            } catch (exception: Throwable) {
              NavigationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.back$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.back()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.returnToNativeHost$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.returnToNativeHost{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NavigationApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(NavigationApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.snabbit_runner.NavigationHostApi.exitNativeShell$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.exitNativeShell()
              listOf(null)
            } catch (exception: Throwable) {
              NavigationApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class NavigationApiPigeonStreamHandler<T>(
    val wrapper: NavigationApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface NavigationApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * KMP → Dart (event channel). Stream of commands the native host emits for
 * Flutter to execute.
 */
abstract class NavCommandsStreamHandler : NavigationApiPigeonEventChannelWrapper<NavCommand> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: NavCommandsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.snabbit_runner.NavigationEventApi.navCommands"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = NavigationApiPigeonStreamHandler<NavCommand>(streamHandler)
      EventChannel(messenger, channelName, NavigationApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from NavigationApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<NavCommand>) {}

override fun onCancel(p0: Any?) {}
}
      
