// Mocks generated by Mockito 5.4.6 from annotations
// in snabbit_runner/test/unit/services/iot/background/iot_background_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:snabbit_runner/models/battery_data.dart' as _i5;
import 'package:snabbit_runner/models/device_state_data.dart' as _i9;
import 'package:snabbit_runner/models/location_data.dart' as _i7;
import 'package:snabbit_runner/services/iot/cleanup/cleanup_job.dart' as _i11;
import 'package:snabbit_runner/services/iot/collectors/battery_collector.dart'
    as _i4;
import 'package:snabbit_runner/services/iot/collectors/device_state_collector.dart'
    as _i8;
import 'package:snabbit_runner/services/iot/collectors/location_collector.dart'
    as _i6;
import 'package:snabbit_runner/services/iot/config/config_service.dart' as _i2;
import 'package:snabbit_runner/services/iot/sender/sender.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i2.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get apiEnabled => (super.noSuchMethod(
        Invocation.getter(#apiEnabled),
        returnValue: false,
      ) as bool);

  @override
  int get batteryCollectionInterval => (super.noSuchMethod(
        Invocation.getter(#batteryCollectionInterval),
        returnValue: 0,
      ) as int);

  @override
  int get sendInterval => (super.noSuchMethod(
        Invocation.getter(#sendInterval),
        returnValue: 0,
      ) as int);

  @override
  int get maxBatteryRecords => (super.noSuchMethod(
        Invocation.getter(#maxBatteryRecords),
        returnValue: 0,
      ) as int);

  @override
  int get maxLocationRecords => (super.noSuchMethod(
        Invocation.getter(#maxLocationRecords),
        returnValue: 0,
      ) as int);

  @override
  int get deviceStateCollectionInterval => (super.noSuchMethod(
        Invocation.getter(#deviceStateCollectionInterval),
        returnValue: 0,
      ) as int);

  @override
  int get maxDeviceStateRecords => (super.noSuchMethod(
        Invocation.getter(#maxDeviceStateRecords),
        returnValue: 0,
      ) as int);

  @override
  int get apiTimeout => (super.noSuchMethod(
        Invocation.getter(#apiTimeout),
        returnValue: 0,
      ) as int);

  @override
  int get cleanupInterval => (super.noSuchMethod(
        Invocation.getter(#cleanupInterval),
        returnValue: 0,
      ) as int);

  @override
  int get killSwitchMaxWait => (super.noSuchMethod(
        Invocation.getter(#killSwitchMaxWait),
        returnValue: 0,
      ) as int);

  @override
  bool get fgFallbackEnabled => (super.noSuchMethod(
        Invocation.getter(#fgFallbackEnabled),
        returnValue: false,
      ) as bool);

  @override
  int get fgFallbackStalenessThresholdSeconds => (super.noSuchMethod(
        Invocation.getter(#fgFallbackStalenessThresholdSeconds),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int getLocationInterval(String? status) => (super.noSuchMethod(
        Invocation.method(
          #getLocationInterval,
          [status],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool hasIntervalsChanged(Map<String, int>? oldIntervals) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasIntervalsChanged,
          [oldIntervals],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [BatteryCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockBatteryCollector extends _i1.Mock implements _i4.BatteryCollector {
  MockBatteryCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> collect(
    String? userId, {
    required int? collectionCycleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collect,
          [userId],
          {#collectionCycleId: collectionCycleId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getUnsentCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUnsentCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.BatteryData>> getUnsent(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsent,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i3.Future<List<_i5.BatteryData>>.value(<_i5.BatteryData>[]),
      ) as _i3.Future<List<_i5.BatteryData>>);
}

/// A class which mocks [LocationCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationCollector extends _i1.Mock implements _i6.LocationCollector {
  MockLocationCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> collect(
    String? userId, {
    required int? collectionCycleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collect,
          [userId],
          {#collectionCycleId: collectionCycleId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getUnsentCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUnsentCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i7.LocationData>> getUnsent(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsent,
          [userId],
          {#limit: limit},
        ),
        returnValue:
            _i3.Future<List<_i7.LocationData>>.value(<_i7.LocationData>[]),
      ) as _i3.Future<List<_i7.LocationData>>);

  @override
  _i3.Future<_i7.LocationData?> getLastCollected(
    String? userId, {
    int? maxAgeSeconds = 60,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastCollected,
          [userId],
          {#maxAgeSeconds: maxAgeSeconds},
        ),
        returnValue: _i3.Future<_i7.LocationData?>.value(),
      ) as _i3.Future<_i7.LocationData?>);
}

/// A class which mocks [DeviceStateCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceStateCollector extends _i1.Mock
    implements _i8.DeviceStateCollector {
  MockDeviceStateCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> collect(
    String? userId, {
    required int? collectionCycleId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #collect,
          [userId],
          {#collectionCycleId: collectionCycleId},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getUnsentCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUnsentCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i9.DeviceStateData>> getUnsent(
    String? userId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsent,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i9.DeviceStateData>>.value(
            <_i9.DeviceStateData>[]),
      ) as _i3.Future<List<_i9.DeviceStateData>>);
}

/// A class which mocks [Sender].
///
/// See the documentation for Mockito's code generation for more information.
class MockSender extends _i1.Mock implements _i10.Sender {
  MockSender() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> sendAllData(
    String? userId,
    String? endpoint,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAllData,
          [
            userId,
            endpoint,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [CleanupJob].
///
/// See the documentation for Mockito's code generation for more information.
class MockCleanupJob extends _i1.Mock implements _i11.CleanupJob {
  MockCleanupJob() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> cleanupSentBatteryData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupSentBatteryData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupSentLocationData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupSentLocationData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupSentDeviceStateData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupSentDeviceStateData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupSentData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupSentData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupBatteryData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupBatteryData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupLocationData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupLocationData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupDeviceStateData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupDeviceStateData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> cleanupAllData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #cleanupAllData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteAllUserData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllUserData,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
