/**
 * Builder classes for wallet_data test data.
 *
 * This file contains two types of builders (following Python agent pattern):
 * 1. Entity Builders - For constructing domain objects/entities
 * 2. Parameter Builders - For constructing test input data (configs, maps)
 *
 * The builder pattern makes test input-output relationships crystal clear:
 * - Input: Built with fluent API showing exactly what's being tested
 * - Output: Assertions verify expected behavior based on input
 *
 * Example:
 *   // Clear input construction
 *   final config = BonusConfigBuilder()
 *       .withCriticalDates(['2025-12-25'])
 *       .build();
 *
 *   // Clear expected output
 *   expect(getDayCategory(date, config), DayCategory.critical);
 *
 * Benefits:
 * - Maintainable: Change structure? Update builder once
 * - Readable: Fluent API makes test intent clear
 * - Reusable: Share builders across test files
 *
 * Generated by Flutter Unit Test Agent
 */

import 'package:snabbit_runner/referrals/models/wallet_data.dart';

class WalletDataBuilder {
  // TODO: Add fields matching WalletData constructor

  WalletDataBuilder();

  WalletData build() {
    // TODO: Construct WalletData instance with test data
    return WalletData(
      // TODO: Add constructor parameters
    );
  }

  // Fluent builder methods
  // TODO: Add with* methods for each field
  // Example:
  // WalletDataBuilder withFieldName(Type value) {
  //   _fieldName = value;
  //   return this;
  // }

  // Scenario methods (following Python agent pattern)
  WalletDataBuilder asHighValue() {
    // TODO: Set up high-value scenario
    return this;
  }

  WalletDataBuilder asLowValue() {
    // TODO: Set up low-value scenario
    return this;
  }

  WalletDataBuilder asEdgeCase() {
    // TODO: Set up edge case scenario (nulls, empty collections, etc.)
    return this;
  }
}
