// Mocks generated by Mockito 5.4.6 from annotations
// in snabbit_runner/test/unit/services/runner_http_testable_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:snabbit_runner/services/runner_http_wrapper.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosition_1 extends _i1.SmartFake implements _i3.Position {
  _FakePosition_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IHttpServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHttpServiceWrapper extends _i1.Mock
    implements _i4.IHttpServiceWrapper {
  MockIHttpServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response<dynamic>> get(
    String? url, {
    Map<String, dynamic>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue:
            _i5.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [IGlobalStateWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGlobalStateWrapper extends _i1.Mock
    implements _i4.IGlobalStateWrapper {
  MockIGlobalStateWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String serverPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #serverPath,
          [path],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #serverPath,
            [path],
          ),
        ),
      ) as String);
}

/// A class which mocks [IGeolocatorWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGeolocatorWrapper extends _i1.Mock
    implements _i4.IGeolocatorWrapper {
  MockIGeolocatorWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.LocationPermission> checkPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [],
        ),
        returnValue: _i5.Future<_i3.LocationPermission>.value(
            _i3.LocationPermission.denied),
      ) as _i5.Future<_i3.LocationPermission>);

  @override
  _i5.Future<_i3.Position> getCurrentPosition({
    _i3.LocationAccuracy? desiredAccuracy,
    Duration? timeLimit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
          {
            #desiredAccuracy: desiredAccuracy,
            #timeLimit: timeLimit,
          },
        ),
        returnValue: _i5.Future<_i3.Position>.value(_FakePosition_1(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
            {
              #desiredAccuracy: desiredAccuracy,
              #timeLimit: timeLimit,
            },
          ),
        )),
      ) as _i5.Future<_i3.Position>);
}

/// A class which mocks [IBatteryWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBatteryWrapper extends _i1.Mock implements _i4.IBatteryWrapper {
  MockIBatteryWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> getBatteryLevel() => (super.noSuchMethod(
        Invocation.method(
          #getBatteryLevel,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}
