// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum NavCommandType {
  /// Navigate to a Flutter-owned route ([NavCommand.route] + [NavCommand.args]) —
  /// a terminal handoff (the native host finishes).
  openFlutterRoute,
  /// Push a Flutter route while KEEPING the native host alive behind it (the
  /// reordering round trip). Dismissing it calls [NavigationHostApi.returnToNativeHost].
  pushHostBackedRoute,
  /// The native root-shell host just became the resumed foreground surface —
  /// Dart should drain any deeplink held for the cohort ([NavCommand.route] is
  /// unused/empty). This makes a held deeplink open ON TOP of the now-foreground
  /// shell, so a shell that launches/re-launches never covers it.
  drainDeeplinks,
}

/// A command the native navigation host asks Flutter to execute (KMP → Dart,
/// event channel). Currently the single cross-world action is opening a
/// Flutter-owned route during a native → Flutter handoff.
class NavCommand {
  NavCommand({
    required this.type,
    required this.route,
    this.args,
  });

  NavCommandType type;

  /// Flutter route name. Always set — every command type carries a route.
  String route;

  /// Optional string arguments for the route.
  Map<String?, String?>? args;

  List<Object?> _toList() {
    return <Object?>[
      type,
      route,
      args,
    ];
  }

  Object encode() {
    return _toList();  }

  static NavCommand decode(Object result) {
    result as List<Object?>;
    return NavCommand(
      type: result[0]! as NavCommandType,
      route: result[1]! as String,
      args: (result[2] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(route, other.route) && _deepEquals(args, other.args);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NavCommand(type: $type, route: $route, args: $args)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NavCommandType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NavCommand) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NavCommandType.values[value];
      case 130:
        return NavCommand.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Dart → KMP (method channel). Drives the native (Compose) navigation host.
class NavigationHostApi {
  /// Constructor for [NavigationHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NavigationHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Open a registered native destination (launches the native host). Returns
  /// `true` if a native screen owns the key (and was opened), `false` otherwise —
  /// the caller decides how to handle a `false` (the module renders no error UI).
  Future<bool> openNativeDestination(String key, Map<String?, String?> args) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.openNativeDestination$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key, args]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Open a native destination and await its result (the
  /// `startActivityForResult` equivalent). Completes with the result map the
  /// native screen returned, or `null` if the screen was dismissed without one.
  Future<Map<String?, String?>?> openNativeDestinationForResult(String key, Map<String?, String?> args) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.openNativeDestinationForResult$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key, args]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return (pigeonVar_replyValue as Map<Object?, Object?>?)?.cast<String?, String?>();
  }

  /// Route an already-resolved deep-link value to a native destination.
  /// Returns true if a native screen owns it (and the host was opened); false
  /// lets the Dart DeepLinkRouter keep handling the value as a Flutter route.
  Future<bool> handleResolvedDeeplink(String value, Map<String?, String?> params) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.handleResolvedDeeplink$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[value, params]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Deep-link keep-host handoff for a Flutter-owned destination. When a native
  /// root-shell host is currently live (the MQTT-cohort shell is foreground), it
  /// brings Flutter to front (keeping the host alive behind it) and opens [route]
  /// (+ [args]) as a host-backed route so back returns to the shell; returns `true`.
  /// Returns `false` when no root-shell host is live — the caller then navigates
  /// on Flutter itself (unchanged behaviour for non-cohort runners).
  Future<bool> openDeeplinkViaHost(String route, Map<String?, String?> args) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.openDeeplinkViaHost$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[route, args]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// True when the native root-shell host (the MQTT-cohort bottom-nav shell) is
  /// currently the RESUMED foreground surface. The deeplink router uses this to
  /// HOLD a cohort deeplink until the shell is actually up — so the linked screen
  /// opens ON TOP of the shell (drained on the shell's onResume) instead of being
  /// covered by a shell that launches/re-launches afterward.
  Future<bool> isRootShellForeground() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.isRootShellForeground$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Loan deep-link, native path: ask the RUNNING root-shell (the MQTT-cohort
  /// bottom-nav shell) to switch to the Profile tab and open the native loan sheet.
  /// Loan is migrated — it lives inside the Profile tab, not as a standalone screen,
  /// so this stays on the shell (no keep-host handoff) and signals it in-place.
  /// Returns `true` when the shell took it; `false` when no root-shell host is the
  /// foreground surface — the caller then shows the Flutter loan sheet (unchanged
  /// behaviour for non-cohort runners).
  Future<bool> showLoanInShell() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.showLoanInShell$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Pop the native back stack (the host finishes when it empties, returning to
  /// Flutter — single-active-surface).
  Future<void> back() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.back$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Return to a host-backed native screen the user handed off from (the reordering
  /// round trip). Reorders the live native host to front, or recreates it from its
  /// stashed key+args if the OS reclaimed it while backgrounded.
  Future<void> returnToNativeHost() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.returnToNativeHost$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Forced-logout teardown: finish the native shell (NavigationHostActivity) so the
  /// Flutter login screen — already pushed by handle403() on the Flutter navigator
  /// underneath — becomes the foreground surface. No-op when no native host is alive
  /// (non-cohort runners, or the runner is already on Flutter).
  Future<void> exitNativeShell() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.snabbit_runner.NavigationHostApi.exitNativeShell$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// KMP → Dart (event channel). Stream of commands the native host emits for
/// Flutter to execute.
/// Returns a broadcast [Stream] of events from the `navCommands` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<NavCommand> navCommands( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel navCommandsChannel =
      EventChannel('dev.flutter.pigeon.snabbit_runner.NavigationEventApi.navCommands$instanceName', pigeonMethodCodec);
  return navCommandsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as NavCommand;
  });
}
    
