// Mocks generated by Mockito 5.4.6 from annotations
// in snabbit_runner/test/unit/modules/snabbit_shield/sos_flow_coordinator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:safety_shield/src/models/safety_shield_enums.dart' as _i6;
import 'package:safety_shield/src/models/safety_shield_events.dart' as _i4;
import 'package:safety_shield/src/safety_shield_config.dart' as _i5;
import 'package:safety_shield/src/safety_shield_facade.dart' as _i2;
import 'package:snabbit_runner/modules/snabbit_shield/shield_deterrence_audio.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SafetyShield].
///
/// See the documentation for Mockito's code generation for more information.
class MockSafetyShield extends _i1.Mock implements _i2.SafetyShield {
  MockSafetyShield() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.EncryptedAudioEvent> get onEncryptedAudioReady =>
      (super.noSuchMethod(
        Invocation.getter(#onEncryptedAudioReady),
        returnValue: _i3.Stream<_i4.EncryptedAudioEvent>.empty(),
      ) as _i3.Stream<_i4.EncryptedAudioEvent>);

  @override
  _i3.Stream<_i4.SoSTriggeredEvent> get onSoSTriggered => (super.noSuchMethod(
        Invocation.getter(#onSoSTriggered),
        returnValue: _i3.Stream<_i4.SoSTriggeredEvent>.empty(),
      ) as _i3.Stream<_i4.SoSTriggeredEvent>);

  @override
  _i3.Stream<_i4.PermissionStatusEvent> get onPermissionStatusChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onPermissionStatusChanged),
        returnValue: _i3.Stream<_i4.PermissionStatusEvent>.empty(),
      ) as _i3.Stream<_i4.PermissionStatusEvent>);

  @override
  _i3.Stream<_i4.AccessibilityServiceEvent> get onAccessibilityServiceStatus =>
      (super.noSuchMethod(
        Invocation.getter(#onAccessibilityServiceStatus),
        returnValue: _i3.Stream<_i4.AccessibilityServiceEvent>.empty(),
      ) as _i3.Stream<_i4.AccessibilityServiceEvent>);

  @override
  _i3.Stream<_i4.RecordingStateEvent> get onRecordingStateChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onRecordingStateChanged),
        returnValue: _i3.Stream<_i4.RecordingStateEvent>.empty(),
      ) as _i3.Stream<_i4.RecordingStateEvent>);

  @override
  _i3.Stream<_i4.MonitoringStateEvent> get onMonitoringStateChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onMonitoringStateChanged),
        returnValue: _i3.Stream<_i4.MonitoringStateEvent>.empty(),
      ) as _i3.Stream<_i4.MonitoringStateEvent>);

  @override
  _i3.Stream<_i4.SafetyShieldError> get onError => (super.noSuchMethod(
        Invocation.getter(#onError),
        returnValue: _i3.Stream<_i4.SafetyShieldError>.empty(),
      ) as _i3.Stream<_i4.SafetyShieldError>);

  @override
  _i3.Stream<_i4.InstrumentationEvent> get onInstrumentationEvent =>
      (super.noSuchMethod(
        Invocation.getter(#onInstrumentationEvent),
        returnValue: _i3.Stream<_i4.InstrumentationEvent>.empty(),
      ) as _i3.Stream<_i4.InstrumentationEvent>);

  @override
  _i3.Stream<_i4.NotificationActionEvent> get onNotificationAction =>
      (super.noSuchMethod(
        Invocation.getter(#onNotificationAction),
        returnValue: _i3.Stream<_i4.NotificationActionEvent>.empty(),
      ) as _i3.Stream<_i4.NotificationActionEvent>);

  @override
  _i3.Future<void> initialize(_i5.SafetyShieldConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [config],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> onJobStarted() => (super.noSuchMethod(
        Invocation.method(
          #onJobStarted,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> onJobEnded() => (super.noSuchMethod(
        Invocation.method(
          #onJobEnded,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateAudioConfig({
    required int? durationSec,
    required int? intervalSec,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAudioConfig,
          [],
          {
            #durationSec: durationSec,
            #intervalSec: intervalSec,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateDetectionThresholds({
    double? dbSpikeThreshold,
    double? accelerometerMagnitudeG,
    double? accelerometerWindowSec,
    int? accelerometerCooldownSec,
    double? yamnetConfidenceThreshold,
    List<String>? yamnetTargetClasses,
    double? vadConfidenceThreshold,
    int? yamnetTopK,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDetectionThresholds,
          [],
          {
            #dbSpikeThreshold: dbSpikeThreshold,
            #accelerometerMagnitudeG: accelerometerMagnitudeG,
            #accelerometerWindowSec: accelerometerWindowSec,
            #accelerometerCooldownSec: accelerometerCooldownSec,
            #yamnetConfidenceThreshold: yamnetConfidenceThreshold,
            #yamnetTargetClasses: yamnetTargetClasses,
            #vadConfidenceThreshold: vadConfidenceThreshold,
            #yamnetTopK: yamnetTopK,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> checkAllPermissions() => (super.noSuchMethod(
        Invocation.method(
          #checkAllPermissions,
          [],
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<_i6.SafetyPermissionStatus> checkPermission(
          _i6.SafetyPermission? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [type],
        ),
        returnValue: _i3.Future<_i6.SafetyPermissionStatus>.value(
            _i6.SafetyPermissionStatus.granted),
      ) as _i3.Future<_i6.SafetyPermissionStatus>);

  @override
  _i3.Future<_i6.SafetyPermissionStatus> requestPermission(
          _i6.SafetyPermission? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [type],
        ),
        returnValue: _i3.Future<_i6.SafetyPermissionStatus>.value(
            _i6.SafetyPermissionStatus.granted),
      ) as _i3.Future<_i6.SafetyPermissionStatus>);

  @override
  _i3.Future<Map<String, String>> requestAllPermissions() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestAllPermissions,
          [],
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);

  @override
  _i3.Future<void> startAccelerometerOnly() => (super.noSuchMethod(
        Invocation.method(
          #startAccelerometerOnly,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> startMonitoringOnly() => (super.noSuchMethod(
        Invocation.method(
          #startMonitoringOnly,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopRecording() => (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.RecordingState> getRecordingState() => (super.noSuchMethod(
        Invocation.method(
          #getRecordingState,
          [],
        ),
        returnValue:
            _i3.Future<_i6.RecordingState>.value(_i6.RecordingState.idle),
      ) as _i3.Future<_i6.RecordingState>);

  @override
  _i3.Future<void> startMonitoring() => (super.noSuchMethod(
        Invocation.method(
          #startMonitoring,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stopMonitoring() => (super.noSuchMethod(
        Invocation.method(
          #stopMonitoring,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> confirmSoS() => (super.noSuchMethod(
        Invocation.method(
          #confirmSoS,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> denySoS() => (super.noSuchMethod(
        Invocation.method(
          #denySoS,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deescalateSoS() => (super.noSuchMethod(
        Invocation.method(
          #deescalateSoS,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> triggerManualSoS() => (super.noSuchMethod(
        Invocation.method(
          #triggerManualSoS,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> discardCurrentRecording() => (super.noSuchMethod(
        Invocation.method(
          #discardCurrentRecording,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> discardAESKey() => (super.noSuchMethod(
        Invocation.method(
          #discardAESKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> notifyStreamsReady() => (super.noSuchMethod(
        Invocation.method(
          #notifyStreamsReady,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ShieldDeterrenceAudio].
///
/// See the documentation for Mockito's code generation for more information.
class MockShieldDeterrenceAudio extends _i1.Mock
    implements _i7.ShieldDeterrenceAudio {
  MockShieldDeterrenceAudio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void start({
    required int? delaySecs,
    required bool Function()? isActive,
    _i8.VoidCallback? onPlayed,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #start,
          [],
          {
            #delaySecs: delaySecs,
            #isActive: isActive,
            #onPlayed: onPlayed,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cancel() => super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
